/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dbproduit;

import Authentification.LoginJFrame;
import dbutilisateur.listeUtilisateurJFrame;
import java.awt.event.WindowEvent;
import javax.swing.JFrame;

/**
 *
 * @author USER
 */
public class AcceuilForm extends javax.swing.JFrame {

    /**
     * Creates new form AcceuilForm
     */
    public AcceuilForm() {
        initComponents();
        //LoadFrame();
    }
    NewJFrame newJFrame=new NewJFrame();
    listeUtilisateurJFrame listeUtilisateurJFrame=new listeUtilisateurJFrame();
 //   LoginJFrame loginJFrame=new LoginJFrame();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gérer_Produits = new javax.swing.JToggleButton();
        gérer_Utilisateurs = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        gérer_Produits.setBackground(new java.awt.Color(153, 0, 102));
        gérer_Produits.setFont(new java.awt.Font("Goudy Old Style", 1, 18)); // NOI18N
        gérer_Produits.setForeground(new java.awt.Color(239, 234, 234));
        gérer_Produits.setText("Gérer Produits");
        gérer_Produits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gérer_ProduitsActionPerformed(evt);
            }
        });
        getContentPane().add(gérer_Produits, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, 306, 47));

        gérer_Utilisateurs.setBackground(new java.awt.Color(153, 0, 102));
        gérer_Utilisateurs.setFont(new java.awt.Font("Goudy Old Style", 1, 18)); // NOI18N
        gérer_Utilisateurs.setForeground(new java.awt.Color(239, 234, 234));
        gérer_Utilisateurs.setText("Gérer Utilisateurs");
        gérer_Utilisateurs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gérer_UtilisateursActionPerformed(evt);
            }
        });
        getContentPane().add(gérer_Utilisateurs, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 350, 306, 47));

        jLabel1.setFont(new java.awt.Font("Goudy Old Style", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(241, 215, 142));
        jLabel1.setText("Beauty  Maker");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 290, 66));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/e8.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 770, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gérer_ProduitsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gérer_ProduitsActionPerformed
        newJFrame.setVisible(true);
        newJFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE );
    }//GEN-LAST:event_gérer_ProduitsActionPerformed

    private void gérer_UtilisateursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gérer_UtilisateursActionPerformed
        // TODO add your handling code here:
        listeUtilisateurJFrame.setVisible(true);
        listeUtilisateurJFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE );
    }//GEN-LAST:event_gérer_UtilisateursActionPerformed

    public void LoadFrame(){
      //  loginJFrame.dispatchEvent(new WindowEvent(this,WindowEvent.WINDOW_CLOSING));
    }
    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AcceuilForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AcceuilForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AcceuilForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AcceuilForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AcceuilForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton gérer_Produits;
    private javax.swing.JToggleButton gérer_Utilisateurs;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
