/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dbproduit;

import java.awt.Image;
import java.awt.event.WindowEvent;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author USER
 */
public class ModifierProduitJFrame extends javax.swing.JFrame {

    /**
     * Creates new form updateProduit
     */
    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    String selectedImagePath;
    File selectedImageFile;
    String promo;
    String linkImage;
    public ModifierProduitJFrame() {
        initComponents();
        Connect();
        LoadModifier();
        viewSeletedRow.setVisible(false);
    }
    public void LoadModifier(){
        if (promo=="Vraix"){ jRadioButtonTrue.setSelected(true);
        jRadioButtonFalse.setSelected(false);}
        else if (promo=="Faux"){jRadioButtonFalse.setSelected(true);
        jRadioButtonTrue.setSelected(false);}
    }
    // NewJFrame newJFrame=new NewJFrame();
    public void Connect() {
        //  newJFrame.Connect();
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");

            con = DriverManager.getConnection("jdbc:mysql://localhost/dbproduit", "root", "root");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ProduitJfram.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ProduitJfram.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtnom = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtqte = new javax.swing.JTextField();
        txtprix = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jRadioButtonTrue = new javax.swing.JRadioButton();
        jRadioButtonFalse = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtdescription = new javax.swing.JTextArea();
        Modifier = new javax.swing.JButton();
        viewSeletedRow = new javax.swing.JLabel();
        txtcouleur = new javax.swing.JTextField();
        jLabelImage = new javax.swing.JLabel();
        selectImage = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Goudy Old Style", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nom Produit");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 90, 29));

        jLabel2.setFont(new java.awt.Font("Goudy Old Style", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Modifier Produit");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, 330, 50));
        getContentPane().add(txtnom, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 256, 29));

        jLabel3.setFont(new java.awt.Font("Goudy Old Style", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Couleur");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 84, 29));

        jLabel4.setFont(new java.awt.Font("Goudy Old Style", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Quantité ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 84, 29));

        jLabel5.setFont(new java.awt.Font("Goudy Old Style", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Prix");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 84, 29));

        jLabel6.setFont(new java.awt.Font("Goudy Old Style", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Description");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 84, 29));
        getContentPane().add(txtqte, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 256, 29));
        getContentPane().add(txtprix, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 256, 29));

        jLabel7.setFont(new java.awt.Font("Goudy Old Style", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Promotion");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 84, 29));

        buttonGroup1.add(jRadioButtonTrue);
        jRadioButtonTrue.setFont(new java.awt.Font("Goudy Old Style", 1, 16)); // NOI18N
        jRadioButtonTrue.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonTrue.setText("Oui");
        getContentPane().add(jRadioButtonTrue, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, 65, -1));

        buttonGroup1.add(jRadioButtonFalse);
        jRadioButtonFalse.setFont(new java.awt.Font("Goudy Old Style", 1, 16)); // NOI18N
        jRadioButtonFalse.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonFalse.setText("Non");
        getContentPane().add(jRadioButtonFalse, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, 63, -1));

        txtdescription.setColumns(20);
        txtdescription.setRows(5);
        jScrollPane2.setViewportView(txtdescription);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 410, 256, 77));

        Modifier.setBackground(new java.awt.Color(238, 208, 238));
        Modifier.setFont(new java.awt.Font("Goudy Old Style", 1, 14)); // NOI18N
        Modifier.setText("Modifier");
        Modifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifierActionPerformed(evt);
            }
        });
        getContentPane().add(Modifier, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 480, 140, 40));
        getContentPane().add(viewSeletedRow, new org.netbeans.lib.awtextra.AbsoluteConstraints(573, 502, 306, 43));
        getContentPane().add(txtcouleur, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 256, 29));

        jLabelImage.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabelImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 170, 252, 218));

        selectImage.setFont(new java.awt.Font("Goudy Old Style", 0, 14)); // NOI18N
        selectImage.setText("Sélectionner Image");
        selectImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectImageActionPerformed(evt);
            }
        });
        getContentPane().add(selectImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 130, 131, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/e9.jpg"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 840, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void ModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifierActionPerformed
        // TODO add your handling code here:
        try {
            String pname = txtnom.getText();
            String price = txtprix.getText();
            String qty = txtqte.getText();
            String color = txtcouleur.getText();
            String descip = txtdescription.getText();
            // = txtpromo.getText();
            String idprod = viewSeletedRow.getText();//txtpid.getSelectedItem().toString();
            String image; //= selectedImageFile.getAbsolutePath();
             ImageIcon imageicon=new ImageIcon(selectedImagePath);
              if(jRadioButtonTrue.isSelected())
            {   promo="Vraix";   }
            else{   promo="Faux";     }
             
              //verifier si l'image a été modifier ou nn
              if(selectedImageFile!=null)
              {image=selectedImageFile.getAbsolutePath();
               }
              else{
                  image=linkImage;
              }
            pst = con.prepareStatement("update produit set pname=?, price=?, qty=?, promo=?, description=?, couleur=?, image=? where idprod=?");

            pst.setString(1, pname);
            pst.setString(2, price);
            pst.setString(3, qty);
            pst.setString(4, promo);
            pst.setString(5, descip);
            pst.setString(6, color);
            pst.setString(7,image);
            pst.setString(8, idprod);
            int k = pst.executeUpdate();
            if (k == 1) {
                JOptionPane.showMessageDialog(this, "Record has been successfully updated!!");
                txtnom.setText("");
                txtprix.setText("");
                txtqte.setText("");
                //txtnom.requestFocus();
                txtdescription.setText("");
                //txtpromo.setText("");
                txtcouleur.setText("");
                // fermer la fenetre lorsque la modification réalisée avec succes
                this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
                //LoadProduitNo();
            } else {
                JOptionPane.showMessageDialog(this, "Record has been failed to update!!");
            }
        } catch (SQLException ex) {
            Logger.getLogger(ProduitJfram.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ModifierActionPerformed

    private void selectImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectImageActionPerformed
        // TODO add your handling code here:
        //setting default browser locations
        JFileChooser browseImageFile = new JFileChooser("C:\\Users\\USER\\Desktop\\ANIME\\anime Images");
        //Filter Image extensions
        FileNameExtensionFilter fnef = new FileNameExtensionFilter("IMAGES", "png", "jpg", "jpeg");
        browseImageFile.addChoosableFileFilter(fnef);
        int showOpenDialogue = browseImageFile.showOpenDialog(null);
        if (showOpenDialogue == JFileChooser.APPROVE_OPTION) {
            selectedImageFile = browseImageFile.getSelectedFile();
            selectedImagePath = selectedImageFile.getAbsolutePath();
            JOptionPane.showMessageDialog(null, selectedImagePath);
            //Display image on jlable
            ImageIcon imgIcon = new ImageIcon(selectedImagePath);
            //Resize image to fit jlabel
            Image image = imgIcon.getImage().getScaledInstance(jLabelImage.getWidth(), jLabelImage.getHeight(), Image.SCALE_SMOOTH);
            jLabelImage.setIcon(new ImageIcon(image));
        }
    }//GEN-LAST:event_selectImageActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModifierProduitJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModifierProduitJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModifierProduitJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModifierProduitJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModifierProduitJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Modifier;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    public javax.swing.JLabel jLabelImage;
    private javax.swing.JList<String> jList1;
    public javax.swing.JRadioButton jRadioButtonFalse;
    public javax.swing.JRadioButton jRadioButtonTrue;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton selectImage;
    public javax.swing.JTextField txtcouleur;
    public javax.swing.JTextArea txtdescription;
    public javax.swing.JTextField txtnom;
    public javax.swing.JTextField txtprix;
    public javax.swing.JTextField txtqte;
    public javax.swing.JLabel viewSeletedRow;
    // End of variables declaration//GEN-END:variables
}
