/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dbproduit;

import java.awt.Component;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author USER
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
Connection con;
PreparedStatement pst;
ResultSet rs;
  DefaultTableModel model;
    public NewJFrame() {
        initComponents();
        //calling method to add column headers to jtable1
        addTableHeader();
        Connect();  
        AfficherList();
    }
     public void Connect(){
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
           
            con = DriverManager.getConnection("jdbc:mysql://localhost/dbproduit", "root", "root");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ProduitJfram.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ProduitJfram.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
  
      public void AfficherList()
    {
        try {
            JLabel imageLabel=new JLabel();
            
            pst = con.prepareStatement("select * from produit");
            rs=pst.executeQuery();
           // txtpid.removeAllItems();
            
            //caher la case de l'ID
             jTable1.getColumnModel().getColumn(0).setMinWidth(0);
            jTable1.getColumnModel().getColumn(0).setMaxWidth(0);
            jTable1.getColumnModel().getColumn(0).setWidth(0);
            //caher la case de l'image
            jTable1.getColumnModel().getColumn(7).setMinWidth(0);
            jTable1.getColumnModel().getColumn(7).setMaxWidth(0);
            jTable1.getColumnModel().getColumn(7).setWidth(0);
            
            
             model=(DefaultTableModel) jTable1.getModel();
             model.setRowCount(0);
            while(rs.next()){
               
             model.addRow(new String[] {rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7),rs.getString(8)});
        
            }
        } catch (SQLException ex) {
            Logger.getLogger(ProduitJfram.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
ProduitJfram ajouterProduitJFrame=new ProduitJfram();
ModifierProduitJFrame updateProduitJFrame=new ModifierProduitJFrame();
ConsulterProduitJFrame consulterProduitJFrame=new ConsulterProduitJFrame();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        UpdateButton = new javax.swing.JButton();
        Supprimer = new javax.swing.JButton();
        ConsulterProduit = new javax.swing.JButton();
        refreshbutton = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        jLabel1.setText("Liste des produits cosmetiques");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Ajouter");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        UpdateButton.setText("Modifier");
        UpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButtonActionPerformed(evt);
            }
        });

        Supprimer.setText("Supprimer");
        Supprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SupprimerActionPerformed(evt);
            }
        });

        ConsulterProduit.setText("Consulter");
        ConsulterProduit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsulterProduitActionPerformed(evt);
            }
        });

        refreshbutton.setText("REFERSH");
        refreshbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 579, Short.MAX_VALUE)
                        .addGap(37, 37, 37))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(55, 55, 55)
                        .addComponent(UpdateButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ConsulterProduit)
                        .addGap(60, 60, 60)
                        .addComponent(Supprimer)
                        .addGap(67, 67, 67))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(refreshbutton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(173, 173, 173))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(refreshbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(UpdateButton)
                    .addComponent(Supprimer)
                    .addComponent(ConsulterProduit))
                .addGap(44, 44, 44)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
  
    String nomProd="";
    String qteProd="";
    String promo="";
    String prix="";
    String description="";
    String couleur="";
    
    public void addTableHeader(){
        model=(DefaultTableModel) jTable1.getModel();
        Object[] newIdentifiers= new Object[]{"ID","Nom Produit","Prix","Quantite","Promo","Description","Couleur","Image"};
        model.setColumnIdentifiers(newIdentifiers);
      
    }
   
    
    
    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ajouterProduitJFrame.setVisible(true);
        ajouterProduitJFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE );
    }//GEN-LAST:event_jButton1ActionPerformed

    private void UpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButtonActionPerformed
        // TODO add your handling code here:
        updateProduitJFrame.setVisible(true);
        updateProduitJFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE );
      //  GetSelectedRow
      int selectedRowFroNewFrame= jTable1.getSelectedRow();
     // check if thy row is selected
     if(selectedRowFroNewFrame==-1)
     {//dispaly error msg
         updateProduitJFrame.viewSeletedRow.setText("no row selected");
         
     }
     else{
         //clear error msessage first
         updateProduitJFrame.viewSeletedRow.setText(model.getValueAt(selectedRowFroNewFrame, 0).toString());
         System.out.println("selected row value="+selectedRowFroNewFrame);
         updateProduitJFrame.txtnom.setText(model.getValueAt(selectedRowFroNewFrame, 1).toString());
         updateProduitJFrame.txtqte.setText(model.getValueAt(selectedRowFroNewFrame,3).toString());
         updateProduitJFrame.txtprix.setText(model.getValueAt(selectedRowFroNewFrame, 2).toString());
         updateProduitJFrame.txtcouleur.setText(model.getValueAt(selectedRowFroNewFrame, 6).toString());
         updateProduitJFrame.promo=model.getValueAt(selectedRowFroNewFrame, 4).toString();
         updateProduitJFrame.txtdescription.setText(model.getValueAt(selectedRowFroNewFrame, 5).toString());
          ImageIcon imgIcon=new ImageIcon(new ImageIcon(model.getValueAt(selectedRowFroNewFrame, 7).toString()).getImage().getScaledInstance(250, 250, 250));
         updateProduitJFrame.jLabelImage.setIcon(imgIcon);
         updateProduitJFrame.linkImage=model.getValueAt(selectedRowFroNewFrame, 7).toString();
         //updateProduitJFrame.jComboBox1.setc(model.getValueAt(selectedRowFroNewFrame, 6).toString());
        
          
     }
    }//GEN-LAST:event_UpdateButtonActionPerformed

    private void SupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SupprimerActionPerformed
        // TODO add your handling code here:
     int getSelectedRowForDelete=   jTable1.getSelectedRow();
     //check if there's row selected
     if(getSelectedRowForDelete>=0){
         String delId=  model.getValueAt(getSelectedRowForDelete, 0).toString();
         
          try {
            pst = con.prepareStatement("delete from produit where idprod=?");
             pst.setString(1,delId);
           int rs=pst.executeUpdate();
            if(rs==1){
                  JOptionPane.showMessageDialog(null,"Produit Supprimé avec succès");
    
            }
            else{
                 JOptionPane.showMessageDialog(null,"Erreur lors de supprimé ce Produit!!!");
    
            }
        } catch (SQLException ex) {
            Logger.getLogger(ProduitJfram.class.getName()).log(Level.SEVERE, null, ex);
        }
         
         
       }
     
     
    }//GEN-LAST:event_SupprimerActionPerformed

    private void ConsulterProduitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsulterProduitActionPerformed
        // TODO add your handling code here:
         consulterProduitJFrame.setVisible(true);
        consulterProduitJFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE );
      //  GetSelectedRow
      int selectedRowFroViewFrame= jTable1.getSelectedRow();
     // check if thy row is selected
     if(selectedRowFroViewFrame==-1)
     {//dispaly error msg
         updateProduitJFrame.viewSeletedRow.setText("no row selected");
         
     }
         else{
         //clear error msessage first
         //consulterProduitJFrame.viewSeletedRow.setText(model.getValueAt(selectedRowFroNewFrame, 0).toString());
         System.out.println("selected row value="+selectedRowFroViewFrame);
         consulterProduitJFrame.txtnom.setText(model.getValueAt(selectedRowFroViewFrame, 1).toString());
         consulterProduitJFrame.txtqte.setText(model.getValueAt(selectedRowFroViewFrame,3).toString());
         consulterProduitJFrame.txtprix.setText(model.getValueAt(selectedRowFroViewFrame, 2).toString());
         consulterProduitJFrame.txtpromo.setText(model.getValueAt(selectedRowFroViewFrame, 4).toString());
         consulterProduitJFrame.txtcouleur.setText(model.getValueAt(selectedRowFroViewFrame, 6).toString());
         consulterProduitJFrame.txtdescription.setText(model.getValueAt(selectedRowFroViewFrame, 5).toString());
         ImageIcon imgIcon=new ImageIcon(new ImageIcon(model.getValueAt(selectedRowFroViewFrame, 7).toString()).getImage().getScaledInstance(250, 250, 250));
         consulterProduitJFrame.jLabelImage.setIcon(imgIcon);
          consulterProduitJFrame.linkpath.setText(model.getValueAt(selectedRowFroViewFrame, 7).toString());
      
          
     }
        
    }//GEN-LAST:event_ConsulterProduitActionPerformed

    private void refreshbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshbuttonActionPerformed
        // TODO add your handling code here:
                 model.setRowCount(0);  
              AfficherList();
    }//GEN-LAST:event_refreshbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ConsulterProduit;
    private javax.swing.JButton Supprimer;
    private javax.swing.JButton UpdateButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JToggleButton refreshbutton;
    // End of variables declaration//GEN-END:variables
}
