/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dbproduit;
import java.awt.Image;
import java.awt.event.WindowEvent;
import java.io.File;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
/**
 *
 * @author USER
 */
public class ProduitJfram extends javax.swing.JFrame {

    /**
     * Creates new form test1
     */
    public ProduitJfram() {
        initComponents();
        Connect();
        LoadProduitNo();
    }
     Connection con ;
    PreparedStatement pst;
    ResultSet rs;
    String selectedImagePath="";
    File selectedImageFile;
    public void Connect(){
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
           
            con = DriverManager.getConnection("jdbc:mysql://localhost/dbproduit", "root", "root");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ProduitJfram.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ProduitJfram.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void LoadProduitNo()
    {
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        btnajouter = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtdescription = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        txtnom = new javax.swing.JTextField();
        txtqte = new javax.swing.JTextField();
        txtprix = new javax.swing.JTextField();
        jRadioButtonFalse = new javax.swing.JRadioButton();
        jRadioButtonTrue = new javax.swing.JRadioButton();
        txtcouleur = new javax.swing.JTextField();
        jLabelImage = new javax.swing.JLabel();
        selectImage = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnajouter.setBackground(new java.awt.Color(238, 208, 238));
        btnajouter.setFont(new java.awt.Font("Goudy Old Style", 1, 14)); // NOI18N
        btnajouter.setText("Ajouter");
        btnajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnajouterActionPerformed(evt);
            }
        });
        getContentPane().add(btnajouter, new org.netbeans.lib.awtextra.AbsoluteConstraints(647, 436, 158, 35));

        jLabel7.setFont(new java.awt.Font("Goudy Old Style", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Promotion");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 353, 84, 29));

        jLabel4.setFont(new java.awt.Font("Goudy Old Style", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nom Produit");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 131, 90, 29));

        jLabel5.setFont(new java.awt.Font("Goudy Old Style", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Couleur");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 288, 84, 29));

        jLabel6.setFont(new java.awt.Font("Goudy Old Style", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Quantité ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 186, 84, 29));

        jLabel8.setFont(new java.awt.Font("Goudy Old Style", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Prix");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 233, 84, 29));

        jLabel9.setFont(new java.awt.Font("Goudy Old Style", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Description");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 409, 84, 29));

        txtdescription.setColumns(20);
        txtdescription.setRows(5);
        jScrollPane2.setViewportView(txtdescription);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 386, 229, 77));

        jLabel2.setFont(new java.awt.Font("Goudy Old Style", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Ajouter Produit");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 300, 51));
        getContentPane().add(txtnom, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 131, 207, 29));
        getContentPane().add(txtqte, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 186, 207, 29));
        getContentPane().add(txtprix, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 233, 207, 29));

        buttonGroup1.add(jRadioButtonFalse);
        jRadioButtonFalse.setFont(new java.awt.Font("Goudy Old Style", 1, 16)); // NOI18N
        jRadioButtonFalse.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonFalse.setText("Non");
        getContentPane().add(jRadioButtonFalse, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 353, 53, -1));

        buttonGroup1.add(jRadioButtonTrue);
        jRadioButtonTrue.setFont(new java.awt.Font("Goudy Old Style", 1, 16)); // NOI18N
        jRadioButtonTrue.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonTrue.setText("Oui");
        getContentPane().add(jRadioButtonTrue, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 353, 49, -1));
        getContentPane().add(txtcouleur, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 288, 207, 29));

        jLabelImage.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabelImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(542, 172, 252, 210));

        selectImage.setFont(new java.awt.Font("Goudy Old Style", 0, 14)); // NOI18N
        selectImage.setText("Sélectionner Image");
        selectImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectImageActionPerformed(evt);
            }
        });
        getContentPane().add(selectImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(487, 131, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/e9.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnajouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnajouterActionPerformed
        // TODO add your handling code here:
          try {
            String pname = txtnom.getText();
            String price = txtprix.getText();
            String qty = txtqte.getText();
            String color=txtcouleur.getText();
            String descip=txtdescription.getText();
            String image=selectedImageFile.getAbsolutePath();//selectedImagePath;
            String promo;//=txtpromo.getText();
            if(jRadioButtonTrue.isSelected())
            {   promo="Vraix";   }
            else{   promo="Faux";     }
            
            ImageIcon imageicon=new ImageIcon(selectedImagePath);
            
           pst = con.prepareStatement("INSERT INTO produit(pname,price,qty,promo,description,couleur,image) VALUES (?, ?, ?, ?, ?, ?,?)");
            pst.setString(1,pname);
            pst.setString(2,price);
            pst.setString(3,qty);
            pst.setString(4,promo);
            pst.setString(5,descip);
            pst.setString(6,color);
            pst.setString(7,image);
            int k=pst.executeUpdate();
            if(k==1){
                JOptionPane.showMessageDialog(this,"Record Added!! successfully!");
                txtnom.setText("");
                txtprix.setText("");
                txtqte.setText("");
                txtcouleur.setText("");
                txtdescription.setText("");
                //txtpromo.setText("");
                 // fermer la fenetre lorsque l'ajout réalisée avec succes
               this.dispatchEvent(new WindowEvent(this,WindowEvent.WINDOW_CLOSING));
            }else{
                JOptionPane.showMessageDialog(this,"Record Failedto save !!");
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(ProduitJfram.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnajouterActionPerformed

    private void selectImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectImageActionPerformed
        // TODO add your handling code here:
        //setting default browser locations
        
        JFileChooser browseImageFile=new JFileChooser("C:\\");
        //Filter Image extensions
        FileNameExtensionFilter fnef=new FileNameExtensionFilter("IMAGES", "png","jpg","jpeg");
        browseImageFile.addChoosableFileFilter(fnef);
      int showOpenDialogue=  browseImageFile.showOpenDialog(null);
      if(showOpenDialogue==JFileChooser.APPROVE_OPTION)
      {
      selectedImageFile = browseImageFile.getSelectedFile();
     selectedImagePath=selectedImageFile.getAbsolutePath();
     JOptionPane.showMessageDialog(null, selectedImagePath);
     //Display image on jlable
     ImageIcon imgIcon=new ImageIcon(selectedImagePath);
     //Resize image to fit jlabel
     Image image=imgIcon.getImage().getScaledInstance(jLabelImage.getWidth(), jLabelImage.getHeight(), Image.SCALE_SMOOTH);
     jLabelImage.setIcon(new ImageIcon(image));
      }
    }//GEN-LAST:event_selectImageActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProduitJfram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProduitJfram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProduitJfram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProduitJfram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProduitJfram().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnajouter;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelImage;
    private javax.swing.JRadioButton jRadioButtonFalse;
    private javax.swing.JRadioButton jRadioButtonTrue;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton selectImage;
    private javax.swing.JTextField txtcouleur;
    public javax.swing.JTextArea txtdescription;
    public javax.swing.JTextField txtnom;
    public javax.swing.JTextField txtprix;
    public javax.swing.JTextField txtqte;
    // End of variables declaration//GEN-END:variables
}
