/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dbutilisateur;

import dbproduit.ProduitJfram;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;


/**
 *
 * @author USER
 */
public class listeUtilisateurJFrame extends javax.swing.JFrame {

    /**
     * Creates new form listeUtilisateurJFrame
     */
    Connection con;
PreparedStatement pst;
ResultSet rs;
  DefaultTableModel model;
    public listeUtilisateurJFrame() {
        initComponents();
         Connect();  
         addTableHeader();
        AfficherList();
    }
    
     public void Connect(){
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
           
            con = DriverManager.getConnection("jdbc:mysql://localhost/dbproduit", "root", "root");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ProduitJfram.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ProduitJfram.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
     
       public void addTableHeader(){
        model=(DefaultTableModel) jTable1.getModel();
        Object[] newIdentifiers= new Object[]{"ID","Nom","Prenom","Email","Login","Mot De Passe"};
        model.setColumnIdentifiers(newIdentifiers);
    }
    
    
      public void AfficherList()
    {
        try {
            pst = con.prepareStatement("select * from utilisateur");
            rs=pst.executeQuery();
           // txtpid.removeAllItems();
            
             jTable1.getColumnModel().getColumn(0).setMinWidth(0);
            jTable1.getColumnModel().getColumn(0).setMaxWidth(0);
            jTable1.getColumnModel().getColumn(0).setWidth(0);
             model=(DefaultTableModel) jTable1.getModel();
             model.setRowCount(0);
            while(rs.next()){
             model.addRow(new String[] {rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6)});
            }
        } catch (SQLException ex) {
            Logger.getLogger(ProduitJfram.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
AjouterUtilisateurJFrame ajouterUtilisateurJFrame=new AjouterUtilisateurJFrame();
ModifierUtilisateurJFrame modifierUtilisateurJFrame =new ModifierUtilisateurJFrame();
ConsulterUtilisateurJFrame consulterUtilisateurJFrame=new ConsulterUtilisateurJFrame();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        UpdateButton = new javax.swing.JButton();
        Supprimer = new javax.swing.JButton();
        ConsulterUtilisateur = new javax.swing.JButton();
        refreshbutton = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(223, 235, 248));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 102));
        jLabel1.setText("Liste Des Utilisateurs");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setBackground(new java.awt.Color(0, 153, 153));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(236, 230, 230));
        jButton1.setText("Ajouter");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        UpdateButton.setBackground(new java.awt.Color(0, 153, 153));
        UpdateButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        UpdateButton.setForeground(new java.awt.Color(236, 230, 230));
        UpdateButton.setText("Modifier");
        UpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButtonActionPerformed(evt);
            }
        });

        Supprimer.setBackground(new java.awt.Color(0, 153, 153));
        Supprimer.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Supprimer.setForeground(new java.awt.Color(236, 230, 230));
        Supprimer.setText("Supprimer");
        Supprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SupprimerActionPerformed(evt);
            }
        });

        ConsulterUtilisateur.setBackground(new java.awt.Color(0, 153, 153));
        ConsulterUtilisateur.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ConsulterUtilisateur.setForeground(new java.awt.Color(236, 230, 230));
        ConsulterUtilisateur.setText("Consulter");
        ConsulterUtilisateur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsulterUtilisateurActionPerformed(evt);
            }
        });

        refreshbutton.setBackground(new java.awt.Color(204, 204, 255));
        refreshbutton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        refreshbutton.setText("Refresh");
        refreshbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 764, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(UpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ConsulterUtilisateur, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Supprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(refreshbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(178, 178, 178)))
                .addGap(45, 45, 45))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(43, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(refreshbutton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ConsulterUtilisateur, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Supprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ajouterUtilisateurJFrame.setVisible(true);
        ajouterUtilisateurJFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE );
    }//GEN-LAST:event_jButton1ActionPerformed

    private void UpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButtonActionPerformed
        // TODO add your handling code here:
       modifierUtilisateurJFrame.setVisible(true);
        modifierUtilisateurJFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE );
        //  GetSelectedRow
        int selectedRowFroNewFrame= jTable1.getSelectedRow();
        // check if thy row is selected
        if(selectedRowFroNewFrame==-1)
        {//dispaly error msg
            modifierUtilisateurJFrame.viewSeletedRow.setText("no row selected");

        }
        else{
            //clear error msessage first
            modifierUtilisateurJFrame.viewSeletedRow.setText(model.getValueAt(selectedRowFroNewFrame, 0).toString());
            System.out.println("selected row value="+selectedRowFroNewFrame);
            modifierUtilisateurJFrame.txtnom.setText(model.getValueAt(selectedRowFroNewFrame, 1).toString());
            modifierUtilisateurJFrame.txtprenom.setText(model.getValueAt(selectedRowFroNewFrame,2).toString());
            modifierUtilisateurJFrame.txtemail.setText(model.getValueAt(selectedRowFroNewFrame, 3).toString());
            modifierUtilisateurJFrame.txtlogin.setText(model.getValueAt(selectedRowFroNewFrame, 4).toString());
            modifierUtilisateurJFrame.txtpassword.setText(model.getValueAt(selectedRowFroNewFrame, 5).toString());
           
           

        }
    }//GEN-LAST:event_UpdateButtonActionPerformed

    private void SupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SupprimerActionPerformed
        // TODO add your handling code here:
        int getSelectedRowForDelete=   jTable1.getSelectedRow();
        //check if there's row selected
        if(getSelectedRowForDelete>=0){
            String delId=  model.getValueAt(getSelectedRowForDelete, 0).toString();

            try {
                pst = con.prepareStatement("delete from utilisateur where idU=?");
                pst.setString(1,delId);
                int rs=pst.executeUpdate();
                if(rs==1){
                    JOptionPane.showMessageDialog(null,"Produit Supprimé avec succès");

                }
                else{
                    JOptionPane.showMessageDialog(null,"Erreur lors de supprimé ce Produit!!!");

                }
            } catch (SQLException ex) {
                Logger.getLogger(ProduitJfram.class.getName()).log(Level.SEVERE, null, ex);
            }

        }

    }//GEN-LAST:event_SupprimerActionPerformed

    private void ConsulterUtilisateurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsulterUtilisateurActionPerformed
        // TODO add your handling code here:
   consulterUtilisateurJFrame.setVisible(true);
        consulterUtilisateurJFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE );
        //  GetSelectedRow
        int selectedRowFroNewFrame= jTable1.getSelectedRow();
        // check if thy row is selected
        if(selectedRowFroNewFrame==-1)
        {//dispaly error msg
            consulterUtilisateurJFrame.viewSeletedRow.setText("no row selected");

        }
        else{
            //clear error msessage first
            consulterUtilisateurJFrame.viewSeletedRow.setText(model.getValueAt(selectedRowFroNewFrame, 0).toString());
            System.out.println("selected row value="+selectedRowFroNewFrame);
            consulterUtilisateurJFrame.txtnom.setText(model.getValueAt(selectedRowFroNewFrame, 1).toString());
            consulterUtilisateurJFrame.txtprenom.setText(model.getValueAt(selectedRowFroNewFrame,2).toString());
            consulterUtilisateurJFrame.txtemail.setText(model.getValueAt(selectedRowFroNewFrame, 3).toString());
            consulterUtilisateurJFrame.txtlogin.setText(model.getValueAt(selectedRowFroNewFrame, 4).toString());
            consulterUtilisateurJFrame.txtpassword.setText(model.getValueAt(selectedRowFroNewFrame, 5).toString());
        }
    }//GEN-LAST:event_ConsulterUtilisateurActionPerformed

    private void refreshbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshbuttonActionPerformed
        // TODO add your handling code here:
                 model.setRowCount(0);  
              AfficherList();
    
    }//GEN-LAST:event_refreshbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(listeUtilisateurJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(listeUtilisateurJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(listeUtilisateurJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(listeUtilisateurJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new listeUtilisateurJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ConsulterUtilisateur;
    private javax.swing.JButton Supprimer;
    private javax.swing.JButton UpdateButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JToggleButton refreshbutton;
    // End of variables declaration//GEN-END:variables
}
