/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dbutilisateur;

import dbproduit.ProduitJfram;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;


/**
 *
 * @author USER
 */
public class listeUtilisateurJFrame extends javax.swing.JFrame {

    /**
     * Creates new form listeUtilisateurJFrame
     */
    Connection con;
PreparedStatement pst;
ResultSet rs;
  DefaultTableModel model;
    public listeUtilisateurJFrame() {
        initComponents();
         Connect();  
         addTableHeader();
        AfficherList();
    }
    
     public void Connect(){
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
           
            con = DriverManager.getConnection("jdbc:mysql://localhost/dbproduit", "root", "root");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ProduitJfram.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ProduitJfram.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
     
       public void addTableHeader(){
        model=(DefaultTableModel) jTable1.getModel();
        Object[] newIdentifiers= new Object[]{"ID","Nom","Prenom","Email","Adresse","NumeroTel","Login","Mot de passe"};
        model.setColumnIdentifiers(newIdentifiers);
    }
    
    
      public void AfficherList()
    {
        try {
            pst = con.prepareStatement("select * from employe");
            rs=pst.executeQuery();
           // txtpid.removeAllItems();
            
             jTable1.getColumnModel().getColumn(0).setMinWidth(0);
            jTable1.getColumnModel().getColumn(0).setMaxWidth(0);
            jTable1.getColumnModel().getColumn(0).setWidth(0);
             model=(DefaultTableModel) jTable1.getModel();
             model.setRowCount(0);
            while(rs.next()){
             model.addRow(new String[] {rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7),rs.getString(8)});
            }
        } catch (SQLException ex) {
            Logger.getLogger(ProduitJfram.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
AjouterUtilisateurJFrame ajouterUtilisateurJFrame=new AjouterUtilisateurJFrame();
ModifierUtilisateurJFrame modifierUtilisateurJFrame =new ModifierUtilisateurJFrame();
ConsulterUtilisateurJFrame consulterUtilisateurJFrame=new ConsulterUtilisateurJFrame();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Supprimer = new javax.swing.JButton();
        ConsulterUtilisateur = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        refreshbutton = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();
        UpdateButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        viewSeletedRow = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Supprimer.setBackground(new java.awt.Color(253, 227, 227));
        Supprimer.setFont(new java.awt.Font("Goudy Old Style", 1, 16)); // NOI18N
        Supprimer.setText("Supprimer");
        Supprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SupprimerActionPerformed(evt);
            }
        });
        getContentPane().add(Supprimer, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 200, 103, 40));

        ConsulterUtilisateur.setBackground(new java.awt.Color(253, 227, 227));
        ConsulterUtilisateur.setFont(new java.awt.Font("Goudy Old Style", 1, 16)); // NOI18N
        ConsulterUtilisateur.setText("Consulter");
        ConsulterUtilisateur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsulterUtilisateurActionPerformed(evt);
            }
        });
        getContentPane().add(ConsulterUtilisateur, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 200, 100, 39));

        jLabel1.setFont(new java.awt.Font("Goudy Old Style", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(241, 130, 127));
        jLabel1.setText("Liste Des Employées");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 322, 39));

        refreshbutton.setBackground(new java.awt.Color(253, 227, 227));
        refreshbutton.setFont(new java.awt.Font("Goudy Old Style", 1, 16)); // NOI18N
        refreshbutton.setText("Refresh");
        refreshbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(refreshbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 110, 30));

        jButton1.setBackground(new java.awt.Color(253, 227, 227));
        jButton1.setFont(new java.awt.Font("Goudy Old Style", 1, 16)); // NOI18N
        jButton1.setText("Ajouter");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 100, 40));

        UpdateButton.setBackground(new java.awt.Color(253, 227, 227));
        UpdateButton.setFont(new java.awt.Font("Goudy Old Style", 1, 16)); // NOI18N
        UpdateButton.setText("Modifier");
        UpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButtonActionPerformed(evt);
            }
        });
        getContentPane().add(UpdateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 111, 40));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 750, 190));

        viewSeletedRow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/e12.jpg"))); // NOI18N
        getContentPane().add(viewSeletedRow, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 790, 540));

        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 110, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ajouterUtilisateurJFrame.setVisible(true);
        ajouterUtilisateurJFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE );
    }//GEN-LAST:event_jButton1ActionPerformed

    private void UpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButtonActionPerformed
        // TODO add your handling code here:
       modifierUtilisateurJFrame.setVisible(true);
        modifierUtilisateurJFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE );
        //  GetSelectedRow
        int selectedRowFroNewFrame= jTable1.getSelectedRow();
        // check if thy row is selected
        if(selectedRowFroNewFrame==-1)
        {//dispaly error msg
            modifierUtilisateurJFrame.viewSeletedRow.setText("no row selected");

        }
        else{
            //clear error msessage first
            modifierUtilisateurJFrame.viewSeletedRow.setText(model.getValueAt(selectedRowFroNewFrame, 0).toString());
            System.out.println("selected row value="+selectedRowFroNewFrame);
            modifierUtilisateurJFrame.txtnom.setText(model.getValueAt(selectedRowFroNewFrame, 1).toString());
            modifierUtilisateurJFrame.txtprenom.setText(model.getValueAt(selectedRowFroNewFrame,2).toString());
            modifierUtilisateurJFrame.txtemail.setText(model.getValueAt(selectedRowFroNewFrame, 3).toString());
            modifierUtilisateurJFrame.txtadresse.setText(model.getValueAt(selectedRowFroNewFrame, 4).toString());
            modifierUtilisateurJFrame.txtnum.setText(model.getValueAt(selectedRowFroNewFrame, 5).toString());
            modifierUtilisateurJFrame.txtlogin.setText(model.getValueAt(selectedRowFroNewFrame, 6).toString());
            modifierUtilisateurJFrame.txtpassword.setText(model.getValueAt(selectedRowFroNewFrame, 7).toString());
           
           

        }
    }//GEN-LAST:event_UpdateButtonActionPerformed

    private void SupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SupprimerActionPerformed
        // TODO add your handling code here:
        int getSelectedRowForDelete=   jTable1.getSelectedRow();
        //check if there's row selected
        if(getSelectedRowForDelete>=0){
            String delId=  model.getValueAt(getSelectedRowForDelete, 0).toString();

            try {
                pst = con.prepareStatement("delete from employe where idE=?");
                pst.setString(1,delId);
                int rs=pst.executeUpdate();
                if(rs==1){
                    JOptionPane.showMessageDialog(null,"Employé Supprimé avec succès");

                }
                else{
                    JOptionPane.showMessageDialog(null,"Erreur lors de supprimé ce Employé!!!");

                }
            } catch (SQLException ex) {
                Logger.getLogger(ProduitJfram.class.getName()).log(Level.SEVERE, null, ex);
            }

        }

    }//GEN-LAST:event_SupprimerActionPerformed

    private void ConsulterUtilisateurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsulterUtilisateurActionPerformed
        // TODO add your handling code here:
   consulterUtilisateurJFrame.setVisible(true);
        consulterUtilisateurJFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE );
        //  GetSelectedRow
        int selectedRowFroNewFrame= jTable1.getSelectedRow();
        // check if thy row is selected
        if(selectedRowFroNewFrame==-1)
        {//dispaly error msg
            consulterUtilisateurJFrame.viewSeletedRow.setText("no row selected");

        }
        else{
            //clear error msessage first
            consulterUtilisateurJFrame.viewSeletedRow.setText(model.getValueAt(selectedRowFroNewFrame, 0).toString());
            System.out.println("selected row value="+selectedRowFroNewFrame);
            consulterUtilisateurJFrame.txtnom.setText(model.getValueAt(selectedRowFroNewFrame, 1).toString());
            consulterUtilisateurJFrame.txtprenom.setText(model.getValueAt(selectedRowFroNewFrame,2).toString());
            consulterUtilisateurJFrame.txtemail.setText(model.getValueAt(selectedRowFroNewFrame, 3).toString());
            consulterUtilisateurJFrame.txtadresse.setText(model.getValueAt(selectedRowFroNewFrame, 4).toString());
            consulterUtilisateurJFrame.txtnum.setText(model.getValueAt(selectedRowFroNewFrame, 5).toString());
            consulterUtilisateurJFrame.txtlogin.setText(model.getValueAt(selectedRowFroNewFrame, 6).toString());
            consulterUtilisateurJFrame.txtpassword.setText(model.getValueAt(selectedRowFroNewFrame, 7).toString());
        }
    }//GEN-LAST:event_ConsulterUtilisateurActionPerformed

    private void refreshbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshbuttonActionPerformed
        // TODO add your handling code here:
                 model.setRowCount(0);  
              AfficherList();
    
    }//GEN-LAST:event_refreshbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(listeUtilisateurJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(listeUtilisateurJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(listeUtilisateurJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(listeUtilisateurJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new listeUtilisateurJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ConsulterUtilisateur;
    private javax.swing.JButton Supprimer;
    private javax.swing.JButton UpdateButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JToggleButton refreshbutton;
    private javax.swing.JLabel viewSeletedRow;
    // End of variables declaration//GEN-END:variables
}
