/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dbutilisateur;

import dbproduit.ProduitJfram;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class ModifierUtilisateurJFrame extends javax.swing.JFrame {

    /**
     * Creates new form ModifierUtilisateurJFrame
     */
     Connection con;
PreparedStatement pst;
ResultSet rs;

    public ModifierUtilisateurJFrame() {
        initComponents();
        Connect();
    }
  //  listeUtilisateurJFrame listeUtilisateurJFrame=new listeUtilisateurJFrame();
 public void Connect(){
    // listeUtilisateurJFrame.Connect();
      try {
            Class.forName("com.mysql.cj.jdbc.Driver");
           
            con = DriverManager.getConnection("jdbc:mysql://localhost/dbproduit", "root", "root");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ProduitJfram.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ProduitJfram.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        modifierBoutton = new javax.swing.JButton();
        txtnom = new javax.swing.JTextField();
        txtprenom = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        txtadresse = new javax.swing.JTextField();
        txtnum = new javax.swing.JTextField();
        txtlogin = new javax.swing.JTextField();
        txtpassword = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        viewSeletedRow = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        modifierBoutton.setBackground(new java.awt.Color(253, 227, 227));
        modifierBoutton.setFont(new java.awt.Font("Goudy Old Style", 1, 14)); // NOI18N
        modifierBoutton.setText("Modifer");
        modifierBoutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifierBouttonActionPerformed(evt);
            }
        });
        getContentPane().add(modifierBoutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 480, 147, 40));
        getContentPane().add(txtnom, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 128, 230, 29));
        getContentPane().add(txtprenom, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 175, 230, 30));
        getContentPane().add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 222, 230, 34));
        getContentPane().add(txtadresse, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 274, 230, 31));
        getContentPane().add(txtnum, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 322, 230, 33));

        txtlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtloginActionPerformed(evt);
            }
        });
        getContentPane().add(txtlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 388, 230, 29));
        getContentPane().add(txtpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 435, 230, 29));

        jLabel1.setBackground(new java.awt.Color(241, 130, 127));
        jLabel1.setFont(new java.awt.Font("Goudy Old Style", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(241, 130, 127));
        jLabel1.setText("Modifier Employé");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 46, 294, 39));

        jLabel4.setFont(new java.awt.Font("Goudy Old Style", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nom");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 84, 29));

        jLabel6.setFont(new java.awt.Font("Goudy Old Style", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Prenom");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 84, 29));

        jLabel8.setFont(new java.awt.Font("Goudy Old Style", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Email");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 84, 29));

        jLabel2.setFont(new java.awt.Font("Goudy Old Style", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Adresse");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 58, 25));

        jLabel3.setFont(new java.awt.Font("Goudy Old Style", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Numéro de téléphone");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, 141, 22));

        jLabel5.setFont(new java.awt.Font("Goudy Old Style", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Login");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 390, 84, 29));

        jLabel7.setFont(new java.awt.Font("Goudy Old Style", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Mot De Passe");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 440, 103, 29));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/e12.jpg"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 570));
        getContentPane().add(viewSeletedRow, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 500, 90, 80));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void modifierBouttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifierBouttonActionPerformed
        // TODO add your handling code here:
        try{ 
            String nom = txtnom.getText();
            String prenom = txtprenom.getText();
            String email = txtemail.getText();
            String adresse=txtadresse.getText();
            String numtel=txtnum.getText();
            String login=txtlogin.getText();
            String pass=txtpassword.getText();
                     
          
            String idEmploye=viewSeletedRow.getText();//txtpid.getSelectedItem().toString();
            pst=con.prepareStatement("UPDATE employe SET nom=?, prenom=?, email=?, adresse=?, numTel=?, login=?, motdepasse=?  WHERE idE=?");
            
            pst.setString(1,nom);
            pst.setString(2,prenom);
            pst.setString(3,email);
            
            pst.setString(4,adresse);
            pst.setString(5,numtel);
            pst.setString(6,login);
            pst.setString(7,pass);
            pst.setString(8,idEmploye);
            
            int k=pst.executeUpdate();
            if(k==1){
                  JOptionPane.showMessageDialog(this,"La mise à jour de l'Employé a été effectué avec succes!!");
                // fermer la fenetre lorsque la modification réalisée avec succes
               this.dispatchEvent(new WindowEvent(this,WindowEvent.WINDOW_CLOSING));
               //LoadProduitNo();
                 }else{
                 JOptionPane.showMessageDialog(this,"Record has been failed to update!!");
            }
        } catch (SQLException ex) {
            Logger.getLogger(ProduitJfram.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_modifierBouttonActionPerformed

    private void txtloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtloginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtloginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModifierUtilisateurJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModifierUtilisateurJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModifierUtilisateurJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModifierUtilisateurJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModifierUtilisateurJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton modifierBoutton;
    public javax.swing.JTextField txtadresse;
    public javax.swing.JTextField txtemail;
    public javax.swing.JTextField txtlogin;
    public javax.swing.JTextField txtnom;
    public javax.swing.JTextField txtnum;
    public javax.swing.JTextField txtpassword;
    public javax.swing.JTextField txtprenom;
    public javax.swing.JLabel viewSeletedRow;
    // End of variables declaration//GEN-END:variables
}
